package Interfaces;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import Project.DBConnect;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author Supun Rasanga
 */
public class Book extends javax.swing.JFrame {
 Connection con =null;
  PreparedStatement pst =null;
  ResultSet rs = null;
    /**
     * Creates new form Book
     */
    public Book() {
        initComponents();
        //Connect to DB 
        con = DBConnect.connect();
         //load to table
        tableload();
       
    }

     public void tableload()
  {
    jTable2.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,12));
     jTable2.getTableHeader().setOpaque(false);
     jTable2.getTableHeader().setBackground(new Color(32, 136,203));
     jTable2.getTableHeader().setForeground(new Color(0,0,0));
     jTable2.setRowHeight(25);
      
     
     
      try{
          String sql = "SELECT BookID As 'Book ID' ,PublisherYear As 'Publisher Year',BookName As 'Book Name',Publisher,Price FROM book";
          pst = con.prepareStatement(sql);
          rs = pst.executeQuery();
          jTable2.setModel(DbUtils.resultSetToTableModel(rs));
          
      }
      catch(Exception e){
          
      }
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        BPRICE = new javax.swing.JTextField();
        PUBNAME = new javax.swing.JTextField();
        BNAME = new javax.swing.JTextField();
        BYEAR = new javax.swing.JTextField();
        BID = new javax.swing.JTextField();
        SEARCH = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(80, 150));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Book ID");
        jLabel5.setMaximumSize(new java.awt.Dimension(122, 17));
        jLabel5.setMinimumSize(new java.awt.Dimension(122, 17));
        jLabel5.setPreferredSize(new java.awt.Dimension(122, 17));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 129, 29));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Publisher Year");
        jLabel9.setMaximumSize(new java.awt.Dimension(122, 17));
        jLabel9.setMinimumSize(new java.awt.Dimension(122, 17));
        jLabel9.setPreferredSize(new java.awt.Dimension(122, 17));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 129, 29));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Book Name");
        jLabel6.setMaximumSize(new java.awt.Dimension(122, 17));
        jLabel6.setMinimumSize(new java.awt.Dimension(122, 17));
        jLabel6.setPreferredSize(new java.awt.Dimension(122, 17));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 130, 29));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Publisher");
        jLabel7.setMaximumSize(new java.awt.Dimension(122, 17));
        jLabel7.setMinimumSize(new java.awt.Dimension(122, 17));
        jLabel7.setPreferredSize(new java.awt.Dimension(122, 17));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 129, 29));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Price (without Rs ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 130, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("And   .00)");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 80, 30));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/save-icon--1.png"))); // NOI18N
        jButton1.setText("Save");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton1.setIconTextGap(10);
        jButton1.setMargin(new java.awt.Insets(2, 10, 2, 5));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 110, 40));

        jButton13.setBackground(new java.awt.Color(204, 204, 204));
        jButton13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/updated (1).png"))); // NOI18N
        jButton13.setText("Update");
        jButton13.setMargin(new java.awt.Insets(1, 0, 1, 4));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, 110, 40));

        jButton11.setBackground(new java.awt.Color(204, 204, 204));
        jButton11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/delete (1).png"))); // NOI18N
        jButton11.setText("Delete");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 430, 105, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setText("ID OR NAME");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, -1, 30));

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/iconfinder_DeleteRed_34218.png"))); // NOI18N
        jButton2.setText("Close");
        jButton2.setIconTextGap(10);
        jButton2.setMargin(new java.awt.Insets(2, 0, 2, 0));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 430, 100, 40));

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/search.png"))); // NOI18N
        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 30, 110, 35));

        BPRICE.setBackground(new java.awt.Color(255, 255, 153));
        BPRICE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BPRICE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPRICEActionPerformed(evt);
            }
        });
        getContentPane().add(BPRICE, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 290, 33));

        PUBNAME.setBackground(new java.awt.Color(255, 255, 153));
        PUBNAME.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PUBNAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PUBNAMEActionPerformed(evt);
            }
        });
        PUBNAME.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PUBNAMEKeyPressed(evt);
            }
        });
        getContentPane().add(PUBNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 290, 33));

        BNAME.setBackground(new java.awt.Color(255, 255, 153));
        BNAME.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BNAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNAMEActionPerformed(evt);
            }
        });
        BNAME.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BNAMEKeyPressed(evt);
            }
        });
        getContentPane().add(BNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 290, 33));

        BYEAR.setBackground(new java.awt.Color(255, 255, 153));
        BYEAR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BYEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BYEARActionPerformed(evt);
            }
        });
        BYEAR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BYEARKeyPressed(evt);
            }
        });
        getContentPane().add(BYEAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 290, 33));

        BID.setBackground(new java.awt.Color(255, 255, 153));
        BID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BIDActionPerformed(evt);
            }
        });
        BID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BIDKeyPressed(evt);
            }
        });
        getContentPane().add(BID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 290, 33));

        SEARCH.setBackground(new java.awt.Color(255, 255, 153));
        SEARCH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SEARCH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SEARCHKeyPressed(evt);
            }
        });
        getContentPane().add(SEARCH, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, 290, 33));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Book ID", "Publisher Year", "Book Name", "Publisher"
            }
        ));
        jTable2.setRowHeight(25);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 680, 320));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/StudentBackground.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String ID =BID.getText();
        String Year =BYEAR.getText();
        String Name =BNAME.getText();
        String Publisher =PUBNAME.getText();
        String Price = BPRICE.getText();

        String FinalPrice = "Rs."+Price+".00";

        try{
            String b =("INSERT INTO book(BookID,PublisherYear,BookName,Publisher,Price)Values('"+ID+"','"+Year+"','"+Name+"','"+Publisher+"','"+FinalPrice+"')");
            pst = con.prepareStatement(b);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Successfully updated");
            setVisible(false);
            new Book().setVisible(true);

        }
        catch (Exception e){

            JOptionPane.showMessageDialog(null, "Not Successfully updated");
            setVisible(false);
            new Book().setVisible(true);

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:

        int x =    JOptionPane.showConfirmDialog(null,"Do you really want to update");

        if(x==0){

            String id = BID.getText();
            String year = BYEAR.getText();
            String name = BNAME.getText();
            String publisher = PUBNAME.getText();
            String price = BPRICE.getText();

            String sql = "UPDATE book SET PublisherYear = '"+year+"',BookName ='"+name+"',Publisher = '"+publisher+"',Price ='"+price+"' WHERE BookID ='"+id+"'";

            try{

                pst = con.prepareStatement(sql);
                pst.execute();

                //load table
                    tableload();

                new Book().setVisible(true);
                setVisible(false);
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,"Do you can't update MemberID");

            }

        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:

        int x = JOptionPane.showConfirmDialog(null,"Do you want to Delete This");

        if(x==0){

            String id = BID.getText();

            String sql = "DELETE FROM book WHERE BookID='"+id+"'";

            try{

                pst = con.prepareStatement(sql);
                pst.execute();

                //load table
                //   tableload();

                new Book().setVisible(true);
                setVisible(false);
            }
            catch(Exception e){
                System.out.println(e);

            }

        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        String Search = SEARCH.getText();

        String sql = "SELECT BookID,PublisherYear,BookName,Publisher,Price FROM book WHERE BookID LIKE '%"+Search +"%' OR BookName LIKE '%"+Search +"%'";

        try{
            pst  = con.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void PUBNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PUBNAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PUBNAMEActionPerformed

    private void BNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BNAMEActionPerformed

    private void BYEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BYEARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BYEARActionPerformed

    private void BIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BIDActionPerformed

    private void BPRICEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPRICEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BPRICEActionPerformed

    private void BIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BIDKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
            BYEAR.requestFocus();
    }//GEN-LAST:event_BIDKeyPressed

    private void BYEARKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BYEARKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
            BNAME.requestFocus();
    }//GEN-LAST:event_BYEARKeyPressed

    private void BNAMEKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BNAMEKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
            PUBNAME.requestFocus();
    }//GEN-LAST:event_BNAMEKeyPressed

    private void PUBNAMEKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PUBNAMEKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
            BPRICE.requestFocus();
    }//GEN-LAST:event_PUBNAMEKeyPressed

    private void SEARCHKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SEARCHKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
              String Search = SEARCH.getText();

        String sql = "SELECT BookID,PublisherYear,BookName,Publisher,Price FROM book WHERE BookID LIKE '%"+Search +"%' OR BookName LIKE '%"+Search +"%'";

        try{
            pst  = con.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){

        }
        }
           
    }//GEN-LAST:event_SEARCHKeyPressed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
         int r = jTable2.getSelectedRow();
         
         String id = jTable2.getValueAt(r, 0).toString();
        String year = jTable2.getValueAt(r, 1).toString();
        String bookname = jTable2.getValueAt(r, 2).toString();
        String publisher = jTable2.getValueAt(r, 3).toString();
        String price = jTable2.getValueAt(r, 4).toString();
        
        
        BID.setText(id);
        BYEAR.setText(year);
        BNAME.setText(bookname);
        PUBNAME.setText(publisher);
        BPRICE.setText(price);
    }//GEN-LAST:event_jTable2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Book().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BID;
    private javax.swing.JTextField BNAME;
    private javax.swing.JTextField BPRICE;
    private javax.swing.JTextField BYEAR;
    private javax.swing.JTextField PUBNAME;
    private javax.swing.JTextField SEARCH;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
