package Interfaces;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import Project.DBConnect;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;

import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author Supun Rasanga
 */
public class Student extends javax.swing.JFrame {
 Connection con =null;
  PreparedStatement pst =null;
  ResultSet rs = null;
    /**
     * Creates new form NewStudent
     */
    public Student() {
        initComponents();
          //Connect to DB 
        con = DBConnect.connect();
        
        //load to table
        tableload();
    }
 public void tableload()
  {
      jTable1.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,12));
     jTable1.getTableHeader().setOpaque(false);
     jTable1.getTableHeader().setBackground(new Color(32, 136,203));
     jTable1.getTableHeader().setForeground(new Color(0,0,0));
     jTable1.setRowHeight(25);
      
      try{
          String sql = "SELECT IndexNumber ,StudentName As 'Full Name',NameWithInitials,PermenetAddress,ParentsName,ContactNumber,Grade,ClassRoom FROM student ORDER BY IndexNumber";
          pst = con.prepareStatement(sql);
          rs = pst.executeQuery();
          jTable1.setModel(DbUtils.resultSetToTableModel(rs));
          
      }
      catch(Exception e){
          
      }
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField13 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        GradeBox1 = new javax.swing.JComboBox();
        GradeBox2 = new javax.swing.JComboBox();
        ContactBox = new javax.swing.JTextField();
        ParentsNameBox = new javax.swing.JTextField();
        AddressBox1 = new javax.swing.JTextField();
        InitialsBox = new javax.swing.JTextField();
        NameBox = new javax.swing.JTextField();
        IndexBox = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(80, 150));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "IndexNumber", "Full Name", "NameWithInitials", "PermenetAddress", "ParentsName", "ContactNumber", "Grade", "ClassRoom"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setRowHeight(25);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 710, 320));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/save-icon--1.png"))); // NOI18N
        jButton1.setText("Save");
        jButton1.setMargin(new java.awt.Insets(12, 0, 10, 4));
        jButton1.setMaximumSize(new java.awt.Dimension(87, 31));
        jButton1.setMinimumSize(new java.awt.Dimension(87, 31));
        jButton1.setPreferredSize(new java.awt.Dimension(87, 31));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 110, 40));

        jButton13.setBackground(new java.awt.Color(204, 204, 204));
        jButton13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/updated (1).png"))); // NOI18N
        jButton13.setText("Update");
        jButton13.setMargin(new java.awt.Insets(1, 0, 1, 4));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 430, 110, 40));

        jButton11.setBackground(new java.awt.Color(204, 204, 204));
        jButton11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/delete (1).png"))); // NOI18N
        jButton11.setText("Delete");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 430, 110, 40));

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/iconfinder_DeleteRed_34218.png"))); // NOI18N
        jButton2.setText("Close");
        jButton2.setIconTextGap(10);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 430, 110, 40));

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/search.png"))); // NOI18N
        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 30, -1, 35));

        jTextField13.setBackground(new java.awt.Color(255, 255, 153));
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        jTextField13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField13KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 290, 33));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel11.setText("ID OR NAME");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 40, 110, -1));

        GradeBox1.setBackground(new java.awt.Color(255, 255, 153));
        GradeBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GradeBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "6", "7", "8", "9", "10", "11" }));
        getContentPane().add(GradeBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 90, 36));

        GradeBox2.setBackground(new java.awt.Color(255, 255, 153));
        GradeBox2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GradeBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C", "D", "E", "F" }));
        GradeBox2.setToolTipText("");
        GradeBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GradeBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(GradeBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 90, 36));

        ContactBox.setBackground(new java.awt.Color(255, 255, 153));
        ContactBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ContactBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ContactBoxKeyPressed(evt);
            }
        });
        getContentPane().add(ContactBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 290, 33));

        ParentsNameBox.setBackground(new java.awt.Color(255, 255, 153));
        ParentsNameBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ParentsNameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParentsNameBoxActionPerformed(evt);
            }
        });
        ParentsNameBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ParentsNameBoxKeyPressed(evt);
            }
        });
        getContentPane().add(ParentsNameBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 290, 33));

        AddressBox1.setBackground(new java.awt.Color(255, 255, 153));
        AddressBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AddressBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressBox1ActionPerformed(evt);
            }
        });
        AddressBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AddressBox1KeyPressed(evt);
            }
        });
        getContentPane().add(AddressBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 290, 33));

        InitialsBox.setBackground(new java.awt.Color(255, 255, 153));
        InitialsBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        InitialsBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                InitialsBoxKeyPressed(evt);
            }
        });
        getContentPane().add(InitialsBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 290, 33));

        NameBox.setBackground(new java.awt.Color(255, 255, 153));
        NameBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameBoxActionPerformed(evt);
            }
        });
        NameBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NameBoxKeyPressed(evt);
            }
        });
        getContentPane().add(NameBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 290, 33));

        IndexBox.setBackground(new java.awt.Color(255, 255, 153));
        IndexBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        IndexBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IndexBoxActionPerformed(evt);
            }
        });
        IndexBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                IndexBoxKeyPressed(evt);
            }
        });
        getContentPane().add(IndexBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 290, 33));

        jLabel1.setBackground(java.awt.Color.red);
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Index Number ");
        jLabel1.setPreferredSize(new java.awt.Dimension(127, 17));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 110, 120, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Full Name");
        jLabel2.setPreferredSize(new java.awt.Dimension(127, 17));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 150, 120, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Name With Initials");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 130, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Permenet Address");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 230, 130, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Parents Name");
        jLabel5.setPreferredSize(new java.awt.Dimension(127, 17));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 270, 120, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Contact Number");
        jLabel4.setPreferredSize(new java.awt.Dimension(127, 17));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 310, 130, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Grade");
        jLabel6.setPreferredSize(new java.awt.Dimension(127, 17));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 350, 110, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/StudentBackground.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:

        int r = jTable1.getSelectedRow();

        String id = jTable1.getValueAt(r, 0).toString();
        String name = jTable1.getValueAt(r, 1).toString();
        String initials = jTable1.getValueAt(r, 2).toString();
        String address = jTable1.getValueAt(r, 3).toString();
        String parents = jTable1.getValueAt(r, 4).toString();
        String contact = jTable1.getValueAt(r, 5).toString();
        String grade = jTable1.getValueAt(r, 6).toString();
        String classroom = jTable1.getValueAt(r, 7).toString();

        IndexBox.setText(id);
        NameBox.setText(name);
        InitialsBox.setText(initials);
        AddressBox1.setText(address);
        ParentsNameBox.setText(parents);
        ContactBox.setText(contact);

        GradeBox1.setSelectedItem(grade);
        GradeBox2.setSelectedItem(classroom);

    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String Index =IndexBox.getText();
        String Name=NameBox.getText();
        String Initials = InitialsBox.getText();
        String Address = AddressBox1.getText();
        String ParentsName = ParentsNameBox.getText();
        String Contact = ContactBox.getText();
        String Grade1 =GradeBox1.getSelectedItem().toString();
        String classroom =GradeBox2.getSelectedItem().toString();

        try{
            String q =("INSERT INTO student(IndexNumber,StudentName,NameWithInitials,PermenetAddress,ParentsName,ContactNumber,Grade,ClassRoom)Values('"+Index+"','"+Name+"','"+Initials+"','"+Address+"','"+ParentsName+"','"+Contact+"','"+Grade1+"','"+classroom+"')");
            pst = con.prepareStatement(q);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Successfully updated");

            //load to table
            tableload();

            new Student().setVisible(true);
            setVisible(false);

        }
        catch (Exception e){

            JOptionPane.showMessageDialog(null, "Incorrect ID or Contact Number");

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:

        int x =    JOptionPane.showConfirmDialog(null,"Do you really want to update");

        if(x==0){

            String id = IndexBox.getText();
            String name = NameBox.getText();
            String initials = InitialsBox.getText();
            String address = AddressBox1.getText();
            String parents = ParentsNameBox.getText();
            String contact = ContactBox.getText();
            String grade = GradeBox1.getSelectedItem().toString();
            String classroom = GradeBox2.getSelectedItem().toString();

            String sql = "UPDATE student SET StudentName = '"+name+"',NameWithInitials ='"+initials+"',PermenetAddress = '"+address+"',ParentsName= '"+parents+"',ContactNumber ='"+contact+"',Grade ='"+grade+"',ClassRoom ='"+classroom+"' WHERE IndexNumber ='"+id+"'";

            try{

                pst = con.prepareStatement(sql);
                pst.execute();

                //load table
                tableload();

                new Student().setVisible(true);
                setVisible(false);
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,"Do you can't update IndexNumber");

            }

        }

    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:

        int x = JOptionPane.showConfirmDialog(null,"Do you want to Delete This");

        if(x==0){

            String id = IndexBox.getText();

            String sql = "DELETE FROM student WHERE IndexNumber='"+id+"'";

            try{

                pst = con.prepareStatement(sql);
                pst.execute();

                //load table
                tableload();

                new Student().setVisible(true);
                setVisible(false);
            }
            catch(Exception e){
                System.out.println(e);

            }

        }

    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String Search = jTextField13.getText();

        String sql = "SELECT IndexNumber ,StudentName,NameWithInitials,PermenetAddress,ParentsName,ContactNumber,Grade,ClassRoom FROM student WHERE IndexNumber LIKE '%"+Search +"%' OR StudentName LIKE '%"+Search +"%'";

        try{
            pst  = con.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){

        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField13KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField13KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){

            String Search = jTextField13.getText();

            String sql = "SELECT IndexNumber ,StudentName,NameWithInitials,PermenetAddress,ParentsName,ContactNumber,Grade,ClassRoom FROM student WHERE IndexNumber LIKE '%"+Search +"%' OR StudentName LIKE '%"+Search +"%'";

            try{
                pst  = con.prepareStatement(sql);
                rs = pst.executeQuery();
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            }
            catch(Exception e){

            }

        }

    }//GEN-LAST:event_jTextField13KeyPressed

    private void GradeBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GradeBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GradeBox2ActionPerformed

    private void ContactBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ContactBoxKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_ContactBoxKeyPressed

    private void ParentsNameBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParentsNameBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ParentsNameBoxActionPerformed

    private void ParentsNameBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ParentsNameBoxKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        ContactBox.requestFocus();
    }//GEN-LAST:event_ParentsNameBoxKeyPressed

    private void AddressBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressBox1ActionPerformed

    private void AddressBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AddressBox1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        ParentsNameBox.requestFocus();
    }//GEN-LAST:event_AddressBox1KeyPressed

    private void InitialsBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InitialsBoxKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        AddressBox1.requestFocus();
    }//GEN-LAST:event_InitialsBoxKeyPressed

    private void NameBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameBoxActionPerformed

    private void NameBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NameBoxKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        InitialsBox.requestFocus();
    }//GEN-LAST:event_NameBoxKeyPressed

    private void IndexBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IndexBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IndexBoxActionPerformed

    private void IndexBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IndexBoxKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        NameBox.requestFocus();
    }//GEN-LAST:event_IndexBoxKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressBox1;
    private javax.swing.JTextField ContactBox;
    private javax.swing.JComboBox GradeBox1;
    private javax.swing.JComboBox GradeBox2;
    private javax.swing.JTextField IndexBox;
    private javax.swing.JTextField InitialsBox;
    private javax.swing.JTextField NameBox;
    private javax.swing.JTextField ParentsNameBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField13;
    // End of variables declaration//GEN-END:variables
}
