package Interfaces;


import Project.DBConnect;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Supun Rasanga
 */
public class Teacher extends javax.swing.JFrame {
    Connection con =null;
  PreparedStatement pst =null;
  ResultSet rs =null;

    /**
     * Creates new form Teacher
     */
    public Teacher() {
        initComponents();
        
        //Connect to DB 
        con = DBConnect.connect();
        
         //load to table
        tableload();
    }
    
    public void tableload()
  {
      jTable2.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,12));
     jTable2.getTableHeader().setOpaque(false);
     jTable2.getTableHeader().setBackground(new Color(32, 136,203));
     jTable2.getTableHeader().setForeground(new Color(0,0,0));
     jTable2.setRowHeight(25);
      
      try{
          String sql = "SELECT IDNumber AS 'ID Number',FullName As 'Full Name',NameWithInitials As 'Name With Initials',PermenetAddress As 'Permenet Address',ContactNumber As 'Contact Number' FROM teacher ";
          pst = con.prepareStatement(sql);
          rs = pst.executeQuery();
          jTable2.setModel(DbUtils.resultSetToTableModel(rs));
          
      }
      catch(Exception e){
          
      }
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        IDBox = new javax.swing.JTextField();
        AddressBox = new javax.swing.JTextField();
        ContactBox = new javax.swing.JTextField();
        NameBox = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        InitialBox = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Teachers Page");
        setLocation(new java.awt.Point(80, 150));
        setMinimumSize(new java.awt.Dimension(1200, 520));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/save-icon--1.png"))); // NOI18N
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 110, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("ID Number");
        jLabel5.setMaximumSize(new java.awt.Dimension(122, 17));
        jLabel5.setMinimumSize(new java.awt.Dimension(122, 17));
        jLabel5.setPreferredSize(new java.awt.Dimension(122, 17));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 129, 29));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Full Name");
        jLabel6.setMaximumSize(new java.awt.Dimension(122, 17));
        jLabel6.setMinimumSize(new java.awt.Dimension(122, 17));
        jLabel6.setPreferredSize(new java.awt.Dimension(122, 17));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 129, 29));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Permenet Address");
        jLabel7.setMaximumSize(new java.awt.Dimension(122, 17));
        jLabel7.setMinimumSize(new java.awt.Dimension(122, 17));
        jLabel7.setPreferredSize(new java.awt.Dimension(122, 17));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 129, 29));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Contact Number");
        jLabel8.setMaximumSize(new java.awt.Dimension(122, 17));
        jLabel8.setMinimumSize(new java.awt.Dimension(122, 17));
        jLabel8.setPreferredSize(new java.awt.Dimension(122, 17));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 129, 29));

        IDBox.setBackground(new java.awt.Color(255, 255, 153));
        IDBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        IDBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDBoxActionPerformed(evt);
            }
        });
        IDBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                IDBoxKeyPressed(evt);
            }
        });
        getContentPane().add(IDBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 290, 33));

        AddressBox.setBackground(new java.awt.Color(255, 255, 153));
        AddressBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AddressBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressBoxActionPerformed(evt);
            }
        });
        AddressBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AddressBoxKeyPressed(evt);
            }
        });
        getContentPane().add(AddressBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 290, 33));

        ContactBox.setBackground(new java.awt.Color(255, 255, 153));
        ContactBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ContactBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactBoxActionPerformed(evt);
            }
        });
        getContentPane().add(ContactBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 290, 33));

        NameBox.setBackground(new java.awt.Color(255, 255, 153));
        NameBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameBoxActionPerformed(evt);
            }
        });
        NameBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NameBoxKeyPressed(evt);
            }
        });
        getContentPane().add(NameBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 290, 33));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Name With Initials");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 130, 34));

        InitialBox.setBackground(new java.awt.Color(255, 255, 153));
        InitialBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        InitialBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InitialBoxActionPerformed(evt);
            }
        });
        InitialBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                InitialBoxKeyPressed(evt);
            }
        });
        getContentPane().add(InitialBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 290, 33));

        jTextField13.setBackground(new java.awt.Color(255, 255, 153));
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        jTextField13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField13KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 290, 33));

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/search.png"))); // NOI18N
        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 30, -1, 35));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Number", "Full Name", "Name With Initials", "Permenet Address", "Contact Number"
            }
        ));
        jTable2.setRowHeight(25);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 680, 320));

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 0, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/iconfinder_DeleteRed_34218.png"))); // NOI18N
        jButton4.setText("Close");
        jButton4.setIconTextGap(10);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 430, 110, 40));

        jButton11.setBackground(new java.awt.Color(204, 204, 204));
        jButton11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/delete (1).png"))); // NOI18N
        jButton11.setText("Delete");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 430, 110, 40));

        jButton13.setBackground(new java.awt.Color(204, 204, 204));
        jButton13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/updated (1).png"))); // NOI18N
        jButton13.setText("Update");
        jButton13.setMargin(new java.awt.Insets(1, 0, 1, 4));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 430, 110, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel11.setText("ID OR NAME");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 29, 120, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/StudentBackground.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String ID = IDBox.getText();
        String Name = NameBox.getText();
        String Initials = InitialBox.getText();
        String Address = AddressBox.getText();
        String Contact = ContactBox.getText();
        try{
              String q =("INSERT INTO teacher(IDNumber,FullName,NameWithInitials,PermenetAddress,ContactNumber)Values('"+ID+"','"+Name+"','"+Initials+"','"+Address+"','"+Contact+"')");
        pst = con.prepareStatement(q);
        pst.execute();
        JOptionPane.showMessageDialog(null, "Successfully updated");
            setVisible(false);
            new Teacher().setVisible(true);
            
        }
        catch (Exception e){
            
           
            
           JOptionPane.showMessageDialog(null, "Incorrect ID or Contact Number");
            
            
        
      
    }          
    }//GEN-LAST:event_jButton2ActionPerformed

    private void IDBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDBoxActionPerformed

    private void AddressBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressBoxActionPerformed

    private void ContactBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactBoxActionPerformed

    private void NameBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameBoxActionPerformed

    private void InitialBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InitialBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InitialBoxActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
           String Search = jTextField13.getText();
        
        String sql = "SELECT IDNumber,FullName,NameWithInitials,PermenetAddress,ContactNumber FROM teacher WHERE IDNumber LIKE '%"+Search +"%' OR FullName LIKE '%"+Search +"%'";
        
            
                try{
           pst  = con.prepareStatement(sql);
        rs = pst.executeQuery();
        jTable2.setModel(DbUtils.resultSetToTableModel(rs)); 
       }
       catch(Exception e){
           
       }
          
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        
         
        int x = JOptionPane.showConfirmDialog(null,"Do you want to Delete This");
        
        if(x==0){
           
            String id = IDBox.getText();
            
            String sql = "DELETE FROM teacher WHERE IDNumber='"+id+"'"; 
            
            try{
             
             pst = con.prepareStatement(sql);
             pst.execute();
             
             //load table
             tableload();
             
             new Teacher().setVisible(true); 
             setVisible(false); 
         }
         catch(Exception e){
             System.out.println(e);
             
             
         }
            
        }
        
        
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        
           
    int x =    JOptionPane.showConfirmDialog(null,"Do you really want to update");
        
    if(x==0){
         
        String id = IDBox.getText();
        String name = NameBox.getText();
        String initials = InitialBox.getText();
        String address = AddressBox.getText();
        String contact = ContactBox.getText();
        
 
    
         String sql = "UPDATE teacher SET FullName = '"+name+"',NameWithInitials ='"+initials+"',PermenetAddress = '"+address+"',ContactNumber ='"+contact+"' WHERE IDNumber ='"+id+"'";
        
         try{
             
             pst = con.prepareStatement(sql);
             pst.execute();
             
             //load table
             tableload();
             
             new Teacher().setVisible(true); 
             setVisible(false); 
         }
         catch(Exception e){
             JOptionPane.showMessageDialog(null,"Do you can't update MemberID");
             
         }
             
    }  
    
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        
          
        int r = jTable2.getSelectedRow();
        
        String id = jTable2.getValueAt(r, 0).toString();
        String name = jTable2.getValueAt(r, 1).toString();
        String initials = jTable2.getValueAt(r, 2).toString();
        String address = jTable2.getValueAt(r, 3).toString();
        String contact = jTable2.getValueAt(r, 4).toString();
      
        
        
        IDBox.setText(id);
        NameBox.setText(name);
        InitialBox.setText(initials);
        AddressBox.setText(address);
        ContactBox.setText(contact);
      
       
      
    }//GEN-LAST:event_jTable2MouseClicked

    private void IDBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IDBoxKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
            NameBox.requestFocus();
    }//GEN-LAST:event_IDBoxKeyPressed

    private void NameBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NameBoxKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==KeyEvent.VK_ENTER)
            InitialBox.requestFocus();
    }//GEN-LAST:event_NameBoxKeyPressed

    private void InitialBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InitialBoxKeyPressed
        // TODO add your handling code here:
           if(evt.getKeyCode()==KeyEvent.VK_ENTER)
            AddressBox.requestFocus();
        
    }//GEN-LAST:event_InitialBoxKeyPressed

    private void AddressBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AddressBoxKeyPressed
        // TODO add your handling code here:
          if(evt.getKeyCode()==KeyEvent.VK_ENTER)
            ContactBox.requestFocus();
        
    }//GEN-LAST:event_AddressBoxKeyPressed

    private void jTextField13KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField13KeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
              String Search = jTextField13.getText();
        
        String sql = "SELECT IDNumber,FullName,NameWithInitials,PermenetAddress,ContactNumber FROM teacher WHERE IDNumber LIKE '%"+Search +"%' OR FullName LIKE '%"+Search +"%'";
        
            
                try{
           pst  = con.prepareStatement(sql);
        rs = pst.executeQuery();
        jTable2.setModel(DbUtils.resultSetToTableModel(rs)); 
       }
       catch(Exception e){
           
       }
          
        }
    }//GEN-LAST:event_jTextField13KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teacher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressBox;
    private javax.swing.JTextField ContactBox;
    private javax.swing.JTextField IDBox;
    private javax.swing.JTextField InitialBox;
    private javax.swing.JTextField NameBox;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField13;
    // End of variables declaration//GEN-END:variables
}
